### NUMPY: Arrays and Matrices

> **NumPy** is an extension to the Python programming language, adding support for large, multi-dimensional (numerical) arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. NumPy is having the full form **"Numeric Python"**.

In [1]:
# importing required module
import numpy as np

### Create arrays

In [13]:
# create ndarrays from lists
# note: every element in the ndarray ultimately will have same data type. (Will be converted to the same datatype if required)
data1 = [11, 22, 33, 44, 55]   # list of all integers
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, 22.5, 33, 44, 55]   # list of all integers
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, 22, 33, 44, 55] 5 <class 'list'> 1964379217344
[11 22 33 44 55] 5 <class 'numpy.ndarray'> 1964382849808 int32

[11, 22.5, 33, 44, 55] 5 <class 'list'> 1964384372608
[11.  22.5 33.  44.  55. ] 5 <class 'numpy.ndarray'> 1964363806544 float64


In [14]:
data1 = [11, 22, '33', 44, 55]   # list of all integers
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, 22, True, 33, 44, False, 55]   # list of all integers
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)
print ()
data1 = [11, 22.5, '33', False, 44, 55]   # list of all integers
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1), id(arr1), arr1.dtype)

[11, 22, '33', 44, 55] 5 <class 'list'> 1964378157632
['11' '22' '33' '44' '55'] 5 <class 'numpy.ndarray'> 1964382850096 <U11

[11, 22, True, 33, 44, False, 55] 7 <class 'list'> 1964374089344
[11 22  1 33 44  0 55] 7 <class 'numpy.ndarray'> 1964382848944 int32

[11, 22.5, '33', False, 44, 55] 6 <class 'list'> 1964331785664
['11' '22.5' '33' 'False' '44' '55'] 6 <class 'numpy.ndarray'> 1964382847984 <U32


In [18]:
print (list(range(1, 5)))   # range function creates a list
data2 = [range(1, 5), range(5, 9)]   # list of lists
print (data2, type(data2))
for list1 in data2:
    for element in list1:
        print (element, end = ", ")
    print()

[1, 2, 3, 4]
[range(1, 5), range(5, 9)] <class 'list'>
1, 2, 3, 4, 
5, 6, 7, 8, 


In [21]:
arr2 = np.array(data2)
print (arr2, type(arr2))
list1 = list(arr2)
print (list1, type(list1))
list1 = arr2.tolist()
print (list1, type(list1))

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
[array([1, 2, 3, 4]), array([5, 6, 7, 8])] <class 'list'>
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>


In [33]:
# examining arrays
arr1 = np.array([22, 11, 44, 33, 55])
print (arr1, type(arr1))
print (arr1.dtype, arr1.shape, len(arr1), arr1.ndim, arr1.size)
arr2 = np.array([[22, 11, 44, 33, 55], [77, 88, 99, 34, 66]])
print (arr2, type(arr2))
print (arr2.dtype, arr2.shape, len(arr2), arr2.ndim, arr2.size)

[22 11 44 33 55] <class 'numpy.ndarray'>
int32 (5,) 5 1 5
[[22 11 44 33 55]
 [77 88 99 34 66]] <class 'numpy.ndarray'>
int32 (2, 5) 2 2 10


In [29]:
var1 = (5)
print (var1, type(var1))
var1 = (5,)
print (var1, type(var1))

5 <class 'int'>
(5,) <class 'tuple'>


In [43]:
# create special arrays
print (np.zeros(10))
print (np.zeros((2, 5)))
print (np.zeros(10).reshape(2, 5))
print (np.zeros(10).astype(int))
print (np.zeros(10, int))
print (np.zeros(10).reshape(2, 5).astype(int))
print (np.zeros(10) + 5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [44]:
print (np.ones(10))
print (np.ones((2, 5)))
print (np.ones(10).reshape(2, 5))
print (np.ones(10).astype(int))
print (np.ones(10, int))
print (np.ones(10).reshape(2, 5).astype(int))
print (np.ones(10) * 5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [59]:
print (np.linspace(0, 1, 5))
print (np.linspace(0, 1, 6))
print (np.linspace(11, 21, 11))
print (np.linspace(0, 1))

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8 1. ]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [54]:
print (np.logspace(0, 3, 4))
print (np.logspace(0, 5, 6))
print (np.logspace(0, 5, 6).astype(int))
print (np.logspace(0, 5, 6, base = 2).astype(int))

[   1.   10.  100. 1000.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
[     1     10    100   1000  10000 100000]
[ 1  2  4  8 16 32]


In [61]:
# help(np.logspace)
# help(np.linspace)

In [64]:
# arange is like range, except it returns an array (but not a list)
int_list = list(range(5))
print (int_list, len(int_list), type(int_list))
int_array = np.arange(5)
print (int_array, len(int_array), type(int_array))
float_array = int_array.astype(float)
print (float_array, len(float_array), type(float_array))

[0, 1, 2, 3, 4] 5 <class 'list'>
[0 1 2 3 4] 5 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] 5 <class 'numpy.ndarray'>


### Reshape

In [74]:
matrix = np.arange(10, dtype = float)
print (matrix, matrix.shape)
matrix = matrix.reshape((2, 5))
print (matrix, matrix.shape)
matrix = matrix.reshape((2, 5)).astype(int)
print (matrix, matrix.shape)
matrix = matrix.astype(int).reshape((2, 5))
print (matrix, matrix.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] (10,)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [82]:
print (matrix)
print (matrix.T)
print (matrix.transpose())
print (matrix.transpose().T)
print (matrix.T.transpose())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [84]:
print (matrix)
print (matrix.flatten())
print (matrix.reshape(10))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [92]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print (matrix)
for item in np.nditer(matrix):
    print (item, end = ", ")
    
print ("\n\nSorted in F-style order (Column Major):")
fmatrix = matrix.copy(order = 'F')
print (fmatrix)
for item in np.nditer(fmatrix):
    print (item, end = ", ")
    
print ("\n\nSorted in C-style order (Row Major):")
cmatrix = matrix.copy(order = 'C')
print (cmatrix)
for item in np.nditer(cmatrix):
    print (item, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 

Sorted in F-style order (Column Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 5.0, 1.0, 6.0, 2.0, 7.0, 3.0, 8.0, 4.0, 9.0, 

Sorted in C-style order (Row Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 

### Append, Insert, Delete and Sort

In [105]:
matrix = np.arange(10, dtype = np.int8)
print (matrix)
matrix = np.append(matrix, [10, 11, 12])
print (matrix)
matrix = np.insert(matrix, 3, [13, 14, 15])
print (matrix)
matrix = np.insert(matrix, 6, [100])
print (matrix)
matrix = np.delete(matrix, [5, 6, 7])
print (matrix)
matrix = np.delete(matrix, range(5, 8))
print (matrix)
matrix = np.sort(matrix)
print (matrix)
matrix = -np.sort(-matrix)
print (matrix)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12]
[  0   1   2  13  14  15 100   3   4   5   6   7   8   9  10  11  12]
[ 0  1  2 13 14  4  5  6  7  8  9 10 11 12]
[ 0  1  2 13 14  7  8  9 10 11 12]
[ 0  1  2  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  2  1  0]


In [107]:
# help(np.sort)

### Concatenation and Stack of Two Arrays

In [115]:
a = np.array([[1, 2], [3, 4]])
print ("First array is:")
print (a)

b = np.array([[5, 6], [7, 8]])
print ("Second array is:")
print (b)
print ()
# both the arrays are of the same dimensions
print ("Joining the two arrays along axis 0:")
# print (np.concatenate((a, b), axis = 0))
print (np.concatenate((a, b)))
print ()
print ("Joining the two arrays along axis 1:")
print (np.concatenate((a, b), axis = 1))

First array is:
[[1 2]
 [3 4]]
Second array is:
[[5 6]
 [7 8]]

Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [118]:
print ('Stack the two arrays along axis 0:')
arr1 = np.stack((a, b), 0)
print (arr1, arr1.shape)

Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


In [119]:
print ('Stack the two arrays along axis 1:')
arr1 = np.stack((a, b), 1)
print (arr1, arr1.shape)

Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] (2, 2, 2)


In [123]:
matrix = np.array([[100, 200, 300, 400]])
print (matrix, matrix.shape, matrix.ndim)
arr = matrix.reshape(-1)
print (arr, arr.shape, arr.ndim)
arr = matrix.reshape(-1, 1, 4)
print (arr, arr.shape, arr.ndim)
arr = matrix.reshape(1, 4, -1)
print (arr, arr.shape, arr.ndim)

[[100 200 300 400]] (1, 4) 2
[100 200 300 400] (4,) 1
[[[100 200 300 400]]] (1, 1, 4) 3
[[[100]
  [200]
  [300]
  [400]]] (1, 4, 1) 3


In [126]:
arr = np.array([11, 22, 33, 44])
print (arr, arr.shape)
arr1 = np.resize(arr, (2, 3))
print (arr1, arr1.shape)
arr1 = np.resize(arr, (2, 5))
print (arr1, arr1.shape)

[11 22 33 44] (4,)
[[11 22 33]
 [44 11 22]] (2, 3)
[[11 22 33 44 11]
 [22 33 44 11 22]] (2, 5)


### Selection

In [133]:
arr1 = np.array([11, 22, 33, 44, 55])
print (arr1)
print (arr1[0], arr1[-5], arr1[1], arr1[-4])
print (arr1[2:], arr1[:3])
print (arr1[::-1])

[11 22 33 44 55]
11 11 22 22
[33 44 55] [11 22 33]
[55 44 33 22 11]


In [140]:
arr2 = np.array([range(1, 5), range(5, 9)])
print (arr2)
print (arr2[1][2], arr2[0, :], arr2[1, :])
print (arr2[:, 2])
print (arr2[:, 1:4])

[[1 2 3 4]
 [5 6 7 8]]
7 [1 2 3 4] [5 6 7 8]
[3 7]
[[2 3 4]
 [6 7 8]]


### Views and Copies

In [146]:
arr = np.arange(10)
print (arr)
print (arr[5:8])
arr[5:8] = 12
print (arr)
arr_view = arr[5:8]
print (arr_view)
arr_view[:] = 25
print (arr, arr_view)
print ()
arr_copy = arr[5:8].copy()
print (arr_copy)
arr_copy[:] = 75
print (arr, arr_copy)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[ 0  1  2  3  4 25 25 25  8  9] [25 25 25]

[25 25 25]
[ 0  1  2  3  4 25 25 25  8  9] [75 75 75]


### Using Boolean Arrays

In [164]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print (arr, arr > 5, ~(arr > 5))
print (arr % 2 == 0)
print (arr[arr % 2 == 0], arr[~(arr % 2 == 0)])
print ((arr >= 3) & (arr <= 8))
print (arr[(arr >= 3) & (arr <= 8)])
arr = np.arange(0, 61)
print (arr)
print (arr[(arr % 2 == 0) & (arr % 3 == 0)])
print (arr[arr % 6 == 0])
print (arr[(arr % 2 == 0) | (arr % 3 == 0)])

[1 2 3 4 5 6 7 8 9] [False False False False False  True  True  True  True] [ True  True  True  True  True False False False False]
[False  True False  True False  True False  True False]
[2 4 6 8] [1 3 5 7 9]
[False False  True  True  True  True  True  True False]
[3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60]
[ 0  6 12 18 24 30 36 42 48 54 60]
[ 0  6 12 18 24 30 36 42 48 54 60]
[ 0  2  3  4  6  8  9 10 12 14 15 16 18 20 21 22 24 26 27 28 30 32 33 34
 36 38 39 40 42 44 45 46 48 50 51 52 54 56 57 58 60]


In [173]:
names = np.array(['Bob', 'Tom', 'Pat', 'Bob'])
print (names)
print (names == 'Bob', names[names == 'Bob'])
print (names != 'Bob', names[names != 'Bob'])
names[names != 'Bob'] = 'Jam'
print (names)
print (np.unique(names))

['Bob' 'Tom' 'Pat' 'Bob']
[ True False False  True] ['Bob' 'Bob']
[False  True  True False] ['Tom' 'Pat']
['Bob' 'Jam' 'Jam' 'Bob']
['Bob' 'Jam']


### Vectorized Operations

In [182]:
nums = np.arange(5)
print (nums)
print (nums * 5)
print (nums + 100)
print (np.sqrt(nums))
print (np.ceil(np.sqrt(nums)))
print (np.floor(np.sqrt(nums)))
nums1 = np.arange(5) + 100
print (nums, nums1)
print (nums + nums1, nums - nums1)
print (np.isnan(nums))

[0 1 2 3 4]
[ 0  5 10 15 20]
[100 101 102 103 104]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 2. 2.]
[0. 1. 1. 1. 2.]
[0 1 2 3 4] [100 101 102 103 104]
[100 102 104 106 108] [-100 -100 -100 -100 -100]
[False False False False False]


In [185]:
nums = np.array([100, 200, np.nan, 400, np.nan, 500.5, 600])
print (nums)
print (np.isnan(nums))

[100.  200.    nan 400.    nan 500.5 600. ]
[False False  True False  True False False]


In [189]:
nums = np.arange(5)
print (nums)
print (np.maximum(nums, np.array([10, -2, 13, -4, 5])))
print (np.minimum(nums, np.array([10, -2, 13, -4, 5])))

[0 1 2 3 4]
[10  1 13  3  5]
[ 0 -2  2 -4  4]


In [205]:
# Pt1(x1, y1), Pt2(x2, y2), Eucledian Distance will be sqrt((x1 - x2)^2 + (y1 - y2)^2)
# randn will generate normalized random numbers, where the average and std. div will be close to 0 and 1 respectively
vect1 = np.random.randn(10000)
print (vect1[:5], np.average(vect1), np.std(vect1))

[-0.47889894 -0.49123317  0.76305834  0.1877669  -1.0473643 ] 0.016709167601290598 1.003255629564469


In [212]:
vect1 = np.random.randn(10)
print (vect1)
vect2 = np.random.randn(10)
print (vect2)
total = 0
for i in range(len(vect1)):
    total = total + (vect1[i] - vect2[i]) ** 2
print (np.sqrt(total))
print (np.sqrt(np.sum((vect1 - vect2) ** 2)))
print (np.sqrt(np.sum(pow(np.subtract(vect1, vect2), 2))))
print (np.linalg.norm(vect1 - vect2))
print (np.linalg.norm(np.subtract(vect1, vect2)))

[ 0.06632879 -0.03086868  0.20629851 -1.75690688  1.05704081 -0.95292745
 -1.50510705  0.45272504  1.2630851   0.40108443]
[-0.68905142  1.16419397  2.38776754  0.66751398  0.23752863  1.95990443
  0.21241495  0.44989046  1.59767796 -0.99132026]
5.176120216833163
5.176120216833163
5.176120216833163
5.176120216833163
5.176120216833163


In [222]:
vect1 = np.random.rand(10)
print (vect1)

[0.090156   0.99450283 0.26036212 0.91722047 0.19922364 0.91059158
 0.55384235 0.7923348  0.4103277  0.73068548]


In [230]:
vect1 = np.random.randn(4, 2)
print (vect1)
print (vect1.mean(), vect1.std())
print (vect1.argmax(), vect1. argmin())
print (vect1.sum(axis = 0))
print (vect1.sum(axis = 1))

[[ 0.1414336  -1.41559259]
 [-1.23035427  0.406281  ]
 [ 1.96731212  1.37284618]
 [ 2.16330241  1.58740483]]
0.6240791612139375 1.3010427708799939
6 1
[3.04169387 1.95093942]
[-1.27415898 -0.82407327  3.3401583   3.75070724]


In [237]:
vect1 = np.random.randn(4, 2)
print (vect1)
print (vect1 > 0)
print ((vect1 > 0).sum())
print ((vect1 > 0).any())
print ((vect1 > 0).all())

[[ 0.95237863  1.03365781]
 [ 0.50812505  0.96066985]
 [-0.8131888  -0.16091605]
 [ 1.07956361  0.6545201 ]]
[[ True  True]
 [ True  True]
 [False False]
 [ True  True]]
6
True
False


In [268]:
np.random.seed(90)
nums = np.random.rand(10)
print (nums)
nums = np.random.randint(0, 5, 10)
print (nums)

[0.1530542  0.15768566 0.98549111 0.90449773 0.18607826 0.26770951
 0.33405116 0.64459187 0.25140724 0.63520639]
[0 0 2 0 0 3 4 4 2 1]


In [252]:
nums = np.random.randint(0, 2, 10)
print (nums)

[0 1 0 1 1 1 0 1 0 0]


### Broadcasting

In [270]:
a1 = np.array([[  0,  0,  0],
               [ 10, 10, 10],
               [ 20, 20, 20],
               [ 30, 30, 30]])
print (a1, type(a1))

a2 = np.array([[0], [10], [20], [30]])
print (a2, type(a2))

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] <class 'numpy.ndarray'>
[[ 0]
 [10]
 [20]
 [30]] <class 'numpy.ndarray'>


In [272]:
b1 = np.array([[  0,  1,  2],
               [  0,  1,  2],
               [  0,  1,  2],
               [  0,  1,  2]])
print (b1, type(b1))

b2 = np.array([0, 1, 2])
print (b2, type(b2))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] <class 'numpy.ndarray'>
[0 1 2] <class 'numpy.ndarray'>


In [274]:
result = a1 + b1
print (result)
result = a1 + b2
print (result)
result = a2 + b1
print (result)
result = a2 + b2
print (result)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [276]:
result = np.add(a1, b1)
print (result)
result = np.add(a1, b2)
print (result)
result = np.add(a2, b1)
print (result)
result = np.add(a2, b2)
print (result)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
